FORMAT: 1A
# Hospital-OS Admin Service Document

List of APIs for Hospital-OS Admin Service.

# Group Diet

## Diet categories [/diet-categories]

### Delete Diet Category [DELETE /diet-categories/{id}]

+ Parameters
    + id (string, required) - b_diet_category_id

+ Request 
     + Headers

            Authentication: 12345
          
+ Response 204